AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

# This template uses SAM: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html
# This assumes you have a method handler in ../src/index.js

Parameters:
  AppName:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      FunctionName: !Sub ${AppName}-lambda-hello-world
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
